### PR TITLE
Add export support for Internet Explorer 11

### PR DESCRIPTION
**Pull request by zalenix**
This will add functionality to the export buttons on Internet Explorer. The buttons were appearing when tested on Chrome, Firefox and Internet Explorer, but were only working correctly on Chrome and Firefox. This commit will fix that.

### CODE REVIEW

**Comment by zalenix** [comment]
This also fixes https://github.com/clarketm/TableExport/issues/43

**Comment by clarketm** [comment]
@zalenix - thanks for the contribution. I'm not the savviest with IE, so I would like a quick clarification. What specific version(s) of IE does this fix?

**Comment by zalenix** [comment]
Thank you for accepting my PR. This commit fixes IE11. To add support for IE10 and Edge, the string needs to be "Windows". I will be creating another PR for that.

`mSaveBlob` directly saves to disk but `msSaveOrOpenBlob` provides the open/save dialog which may be useful.

**Comment by clarketm** [comment]
@zalenix – Ah okay, sounds good. Thank you for both your contribution and explanation.

**Pull request merged**
